version: '3.0'
services:
  spotblock:
    build: .
    ports:
     - '9090:9090'
     - '80:80'
     - '8888:8888'
    command: sh -c "./start_up.sh && ./create_test_accounts.sh && httpd -D FOREGROUND"
  prometheus:
    image: prom/prometheus:latest
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--web.listen-address=0.0.0.0:9000'
    ports:
     - '9000:9000'
  grafana:
    image: grafana/grafana:latest
    ports:
     - '3000:3000'

volumes:
  prometheus_data: {}
  grafana_data: {}
